apiVersion: apps/v1
kind: Deployment
metadata:
  name: highcreation
  labels:
    app: highcreation
spec:
  selector:
    matchLabels:
      app: highcreation
  replicas: 1
  template:
    metadata:
      labels:
        app: highcreation
    spec:
      containers:
        - name: highcreation
          image: ghcr.io/pierre-yves-monnet/c8-highcreation:latest
          imagePullPolicy: Always

          resources:
            limits:
              cpu: 1
              memory: 512M
            requests:
              cpu: 1
              memory: 512M